package me.dejawu.kythera;

import me.dejawu.kythera.runtime.KytheraValue;

import java.util.function.Function;

// this class is used to test runtime constructs and examine generated bytecode
public class Scratch {
    public static void main(String[] args) {
        if(Boolean.getBoolean(args[0])) {
            System.out.println("true");
        } else {
            System.out.println("false");
        }
    }
}
