package me.dejawu.kythera;

import me.dejawu.kythera.runtime.KytheraValue;

// this class is used to test runtime constructs and examine generated bytecode
public class Scratch {
    public static void main(String[] args) {
        KytheraValue.getFnTypeValue(new KytheraValue[]{KytheraValue.INT}, KytheraValue.INT);
    }
}
